/**
 * The factory code-emit — the anti-black-box differentiator.
 *
 * Given a firm, Buttress emits its fleet as real, editable TypeScript the firm
 * OWNS: config, agents, and a run entrypoint, parameterized to that firm's
 * roster, region, and trades. This is the "we hand you a codebase, not a
 * flowchart" claim made concrete — the output opens and runs in any editor.
 *
 * Pure and deterministic: same firm in, same files out.
 */

import type { Firm } from "@/lib/domain";
import { TRADE_LABELS } from "@/lib/domain";

export interface EmittedFile {
  path: string;
  language: "typescript" | "markdown";
  content: string;
}

const slug = (name: string) =>
  name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");

function rosterLiteral(firm: Firm): string {
  return firm.roster.map((r) => `    ${r.trade}: ${r.count},`).join("\n");
}

// --- individual file templates ------------------------------------------

function readme(firm: Firm): string {
  const trades = firm.roster.map((r) => TRADE_LABELS[r.trade]).join(", ");
  return `# ${firm.name} — Buttress Fleet

This is **your** workforce-supply fleet, generated by Buttress and owned by you.
No black box, no flowchart you can't leave — real, editable TypeScript agents.

- **Firm:** ${firm.name}
- **Region:** ${firm.region.city}, ${firm.region.state}
- **Trades covered:** ${trades}

## Layout
- \`config.ts\` — your firm config (roster, region, recruiting thresholds)
- \`agents/forecaster.ts\` — deterministic labor-gap forecaster
- \`agents/campaign.ts\` — recruitment-creative generator for career-switchers
- \`agents/dispatch.ts\` — places credentialed workers onto the demand-creating job
- \`run.ts\` — wires the fleet end to end

Edit anything. It's yours.
`;
}

function config(firm: Firm): string {
  return `// ${firm.name} — fleet configuration. Owned and editable.

export const firm = {
  name: ${JSON.stringify(firm.name)},
  region: { city: ${JSON.stringify(firm.region.city)}, state: ${JSON.stringify(firm.region.state)} },
  // Current headcount per trade — edit as you hire.
  roster: {
${rosterLiteral(firm)}
  } as Record<string, number>,
};

// Only act on gaps at least this large.
export const MIN_GAP_TO_RECRUIT = 3;
`;
}

function forecaster(): string {
  return `import { firm } from "../config";

/** Deterministic labor-gap forecaster. The number is computed in plain code —
 *  never produced by a model — so it is provable and reproducible. */
export function forecastGap(trade: string, peakDemand: number) {
  const available = firm.roster[trade] ?? 0;
  const gap = Math.max(0, peakDemand - available);
  return { trade, region: firm.region, needed: peakDemand, available, gap };
}
`;
}

function campaign(firm: Firm, audience: string[]): string {
  return `import { firm } from "../config";

/** Recruitment-creative generator. Converts career-switchers into a short trade.
 *  Swap in your own model provider — this is your code. */
export const AUDIENCE = ${JSON.stringify(audience)};

export function buildPrompt(trade: string, gapCount: number, neededByDate: string) {
  return [
    \`Write recruitment creative to recruit career-switchers into becoming \${trade}s\`,
    \`for \${firm.name} in \${firm.region.city}, \${firm.region.state}.\`,
    \`Shortage: \${gapCount} needed by \${neededByDate}.\`,
    \`Audience: people leaving fields like \${AUDIENCE.join(", ")}.\`,
    \`Entry path: paid pre-apprenticeship, no experience required.\`,
  ].join("\\n");
}
`;
}

function dispatch(): string {
  return `import { firm } from "../config";

/** Places credentialed workers onto the job that created the demand.
 *  Never assigns more than the gap needs. */
export function dispatch(candidateIds: string[], gap: number, projectId: string) {
  return candidateIds.slice(0, Math.max(0, gap)).map((id) => ({
    candidateId: id,
    projectId,
    firm: firm.name,
  }));
}
`;
}

function run(firm: Firm): string {
  return `import { forecastGap } from "./agents/forecaster";
import { buildPrompt } from "./agents/campaign";
import { dispatch } from "./agents/dispatch";

/** ${firm.name}'s fleet, wired end to end. Run it, read it, change it. */
export function runLoop(trade: string, peakDemand: number, neededByDate: string, leads: string[]) {
  const gap = forecastGap(trade, peakDemand);
  const prompt = buildPrompt(trade, gap.gap, neededByDate);
  const assignments = dispatch(leads, gap.gap, "your-project-id");
  return { gap, prompt, assignments };
}
`;
}

/**
 * Emit the firm's owned fleet. `audience` seeds the campaign agent's targeting
 * (the career-switcher origins). Files are returned in a stable order.
 */
export function emitFleet(
  firm: Firm,
  audience: string[] = ["Retail", "Warehouse / logistics", "Call-center support"],
): EmittedFile[] {
  const base = slug(firm.name);
  return [
    { path: `${base}-fleet/README.md`, language: "markdown", content: readme(firm) },
    { path: `${base}-fleet/config.ts`, language: "typescript", content: config(firm) },
    { path: `${base}-fleet/agents/forecaster.ts`, language: "typescript", content: forecaster() },
    { path: `${base}-fleet/agents/campaign.ts`, language: "typescript", content: campaign(firm, audience) },
    { path: `${base}-fleet/agents/dispatch.ts`, language: "typescript", content: dispatch() },
    { path: `${base}-fleet/run.ts`, language: "typescript", content: run(firm) },
  ];
}
